<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEqcww5X\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEqcww5X/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEqcww5X.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEqcww5X\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEqcww5X\App_KernelDevDebugContainer([
    'container.build_hash' => 'Eqcww5X',
    'container.build_id' => 'ff98bdc9',
    'container.build_time' => 1606936019,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEqcww5X');
